language: go

go: 
 - 1.13
 
env: GO111MODULE=on

script:
  - sh scripts/build.sh

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: builds/*
  skip_cleanup: true
  on:
      repo: webp-sh/webp_server_go
      tags: false
      branch: better-ci