language: go

go: 
 - 1.13
 
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

os:
  - windows
  - osc
  - linux

env: GO111MODULE=on

script:
  - sh scripts/build.sh $TRAVIS_OS_NAME $TRAVIS_CPU_ARCH

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: builds/*
  skip_cleanup: true
  on:
      repo: webp-sh/webp_server_go
      tags: false
      branch: better-ci